### ISSUE TITLE
Does not work with 5.0.x

### ISSUE THREAD

**Issue by GaryAitken** [HugoHasenbein/redmine_all_thumbnails#7]
$ bundle exec rake redmine:plugins:migrate RAILS_ENV=redmine_test
rake aborted!
LoadError: cannot load such file -- redmine_all_thumbnails
/home/xblgx_test/.gem/ruby/3.0.4/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/xblgx_test/.gem/ruby/3.0.4/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/xblgx_test/redmine-5.0.1/plugins/redmine_all_thumbnails/init.rb:59:in `<top (required)>'

**Comment by saint-hh** [comment]
After another attempt to update to Redmine 5.0.3, I can confirm, that _redmine_more_previews_ is running fine. Thank you very much!
Now, with _redmine_all_thumbnails_, I'm running as well into the meantioned problems. I'd be able to test, if you want me to.
